version: '3.9'
services:
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
  rhdh-init:
    image: ${RHDH_IMAGE}
    entrypoint: ["./install-dynamic-plugins.sh", "/dynamic-plugins-root"]
    volumes:
      - './dynamic-plugins:/dynamic-plugins-root:Z'
      - './dynamic-plugins.yaml:/opt/app-root/src/dynamic-plugins.yaml'
  rhdh:
    command: ["--config", "app-config.local.yaml", "--config", "dynamic-plugins-root/app-config.dynamic-plugins.yaml"]
    image: ${RHDH_IMAGE}
    ports:
      - '7007:7007'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET}
      - BASE_URL=${BASE_URL}
      # - LOG_LEVEL=debug
    volumes:
      - './app-config.local.yaml:/opt/app-root/src/app-config.local.yaml'
      - './dynamic-plugins:/opt/app-root/src/dynamic-plugins-root:Z'
      - './dynamic-plugins.yaml:/opt/app-root/src/dynamic-plugins.yaml'
    depends_on:
      rhdh-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
